name: 'Test against supported Faraday minor versions'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        faraday_version: ['1.0.1', '1.1.0', '1.2.0', '1.3.1', '1.4.1', '1.5.1', '1.6.0', '1.7.2', '1.8.0', '1.9.3', '1.10.0', '2.0.1', '2.1.0', '2.2.0', '2.3.0']
    env:
      FARADAY_VERSION: ~> ${{ matrix.faraday_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Ruby ${{ matrix.ruby_version }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.1
      - name: Install dependencies
        run: bundle install
      - name: Run RSpec tests
        run: bundle exec rspec